### ISSUE TITLE
Customizable friction factor [Enchancement]

### ISSUE THREAD

**Issue by Mysticpasta1** [SerrpentDagger/graphing-calculator-sd#3]
I would like a customizable friction factor so it stops feeling that you are always moving on ice.

**Comment by SerrpentDagger** [comment]
This will now be implemented into the next release. Thanks for the suggestion!

(Note that due to computer issues, there will be a slight delay to the next update's release date.)

**Comment by SerrpentDagger** [comment]
Implemented as of version 1.29.11.
